### ISSUE TITLE
`JSONDecodeError` with defaults on any method

### ISSUE THREAD

**Issue by daffidwilde** [alan-turing-institute/reprosyn#60]
I am getting a strange error when creating an instance of any method:

```python
>>> import json
>>> from reprosyn.methods import (
...     CTGAN, DS_BAYNET, DS_INDHIST, DS_PRIVBAYES, IPF, MST, PATEGAN, PRIVBAYES, SYNTHPOP
... )
>>> 
>>> methods = (
...     CTGAN, DS_BAYNET, DS_INDHIST, DS_PRIVBAYES, IPF, MST, PATEGAN, PRIVBAYES, SYNTHPOP
... )
>>> 
>>> for method in methods:
...     try:
...         method()
...     except json.JSONDecodeError as e:
...         print(method, e)
... 
...
<class 'reprosyn.methods.gans.gans.CTGAN'> Extra data: line 1 column 4 (char 3)
<class 'reprosyn.methods.data_synthesiser.wrapper.DS_BAYNET'> Extra data: line 1 column 4 (char 3)
<class 'reprosyn.methods.data_synthesiser.wrapper.DS_INDHIST'> Extra data: line 1 column 4 (char 3)
<class 'reprosyn.methods.data_synthesiser.wrapper.DS_PRIVBAYES'> Extra data: line 1 column 4 (char 3)
<class 'reprosyn.methods.ipf.ipf.IPF'> Extra data: line 1 column 4 (char 3)
<class 'reprosyn.methods.mbi.mst.MST'> Extra data: line 1 column 4 (char 3)
<class 'reprosyn.methods.gans.gans.PATEGAN'> Extra data: line 1 column 4 (char 3)
<class 'reprosyn.methods.mbi.privbayes.PRIVBAYES'> Extra data: line 1 column 4 (char 3)
<class 'reprosyn.methods.synthpop.synthpop.SYNTHPOP'> Extra data: line 1 column 4 (char 3)

```

Is there some sort of issue with the JSON metadata? I get a similar error using another dataset-metadata pair which was based on the Teaching File metadata.

In any case, this shouldn't happen on a fresh install.

Below are the details of the `conda` environment I am using:

```yaml
name: rsyn-audit
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - click=8.0.4
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ipykernel=6.15.2
  - ipython=8.6.0
  - jedi=0.18.1
  - jupyter_client=7.4.7
  - libcxx=14.0.6
  - libffi=3.4.2
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - openssl=1.1.1s
  - packaging=21.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyparsing=3.0.9
  - python=3.9.15
  - python-dateutil=2.8.2
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - tzdata=2022g
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.8
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - absl-py==1.3.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - astunparse==1.6.3
    - attrs==22.1.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - contourpy==1.0.6
    - ctgan==0.2.2.dev0
    - cycler==0.11.0
    - datasynthesizer==0.1.11
    - defusedxml==0.7.1
    - disjoint-set==0.7.3
    - fastjsonschema==2.16.2
    - flatbuffers==22.12.6
    - fonttools==4.38.0
    - fqdn==1.5.1
    - gast==0.4.0
    - google-auth==2.15.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.51.1
    - h5py==3.7.0
    - idna==3.4
    - importlib-metadata==5.1.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.3
    - isoduration==20.11.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-console==6.4.4
    - jupyter-core==5.1.0
    - jupyter-events==0.5.0
    - jupyter-server==2.0.1
    - jupyter-server-terminals==0.4.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.4
    - keras==2.11.0
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - mistune==2.0.4
    - nbclassic==0.4.8
    - nbclient==0.7.2
    - nbconvert==7.2.6
    - nbformat==5.7.0
    - networkx==2.8.8
    - nose==1.3.7
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.23.5
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - pandas==1.5.2
    - pandocfilters==1.5.0
    - pillow==9.3.0
    - platformdirs==2.6.0
    - private-pgm==0.0.1
    - prometheus-client==0.15.0
    - protobuf==3.19.6
    - py-synthpop==0.1.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pyrsistent==0.19.2
    - python-json-logger==2.0.4
    - pytz==2022.6
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - reprosyn==0.1.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - scikit-learn==1.2.0
    - scipy==1.9.3
    - seaborn==0.12.1
    - send2trash==1.8.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.28.0
    - termcolor==2.1.1
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - torch==1.12.1
    - torchvision==0.13.1
    - tqdm==4.64.1
    - traitlets==5.7.0
    - typing-extensions==4.4.0
    - uri-template==1.2.0
    - urllib3==1.26.13
    - validators==0.20.0
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.4
    - wrapt==1.14.1
    - zipp==3.11.0

```
